### ISSUE TITLE
Cannot exclude stories.ts file from auto import

### ISSUE THREAD

**Issue by BrachyKnight** [antfu/unplugin-auto-import#407] opened 2023-07-07 10:01 UTC
### Describe the bug

I'm trying to exclude all *.stories.ts files from the autoimport plugin, since the export is only needed for storybook and nothing else.
I have tried with two methods:
1. Adding the `exclude` property in the config object with an array as follows `[\.stories.ts\.ts$]`;
2. Using a negative lookbehind in the `include` array regex as follows: `include: [/(?<!(stories))(\.[tj]sx?)$/]`
It seems that either they are not working or I am missing something. From the documentation I couln't work out if I am doing something wron

### Reproduction

```AutoImport({ 		/* options */ 		include: [ 			/(?<!(stories))(\.[tj]sx?)$/, // .ts, .tsx, .js, .jsx 		],)}

### System Info

```Shell
System:
    OS: Linux 5.15 Alpine Linux
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1255U
    Memory: 2.84 GB / 4.81 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
    pnpm: 8.6.6 - ~/.nvm/versions/node/v18.15.0/bin/pnpm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-07-08 03:50
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-07-08 03:50 UTC
