### ISSUE TITLE
Error in docker environment packaging

### ISSUE THREAD

**Issue by jintongxuebigdata** [antfu/unplugin-auto-import#159] opened 2022-04-15 06:00 UTC
I have installed it. There is no problem when packaging locally, but there is an error when packaging in the docker environment.
The error message is:
Error:[auto-import] failed to loaded @vueuse/core,have you installed it?

**Comment by jintongxuebigdata** [comment] 2022-04-15 06:05
```js
import autoImport from 'unplugin-auto-import/vite';

autoImport({
  imports: ['vue', 'vue-router', '@vueuse/core', '@vueuse/head'],
  dts: 'types/auto-import.d.ts',
}),
```

**Comment by antfu** [comment] 2022-04-15 06:25
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2022-04-15 06:25 UTC
