### ISSUE TITLE
injectAtEnd error

### ISSUE THREAD

**Issue by stuta** [antfu/unplugin-auto-import#316] opened 2023-02-01 16:57 UTC
### Describe the bug

New version with injectAtEnd: true prevents dynamic components to be imported In Vue + Vite. The home page loads, but the login component does not load. When I try to build the project almost all files give an error: ```'import' and 'export' may only appear at the top level (Note that you need plugins to import files that are not JavaScript)```.

Can we have injectAtEnd: false as an option in the config?

### Reproduction

Too big

### System Info

```Shell
System:
    OS: macOS 13.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 60.27 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.5.0 - ~/.nvm/versions/node/v19.5.0/bin/node
    npm: 9.3.1 - ~/.nvm/versions/node/v19.5.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Edge: 109.0.1518.70
    Firefox Developer Edition: 110.0
    Safari: 16.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-02-07 10:24
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-02-07 10:24 UTC

**Comment by stuta** [comment] 2023-02-08 14:58
I can't create reproduction from the vast business repo.
Simply setting injectAtEnd: false fixes this error. Please add it as an option.
