### ISSUE TITLE
Cannot find some module in the build

### ISSUE THREAD

**Issue by shellingfordly** [antfu/unplugin-auto-import#189] opened 2022-05-31 02:10 UTC
<img width="730" alt="image" src="https://user-images.githubusercontent.com/39196952/171078884-4edcaa1b-a2e2-4a9d-9af2-35db01d9724f.png">
<img width="727" alt="image" src="https://user-images.githubusercontent.com/39196952/171078908-e0ed696d-8a26-4aee-8417-ab7f1c93da0a.png">
<img width="732" alt="image" src="https://user-images.githubusercontent.com/39196952/171078935-c4e3d2e5-0662-4eb8-bda4-8d6db6400af7.png">

**Comment by antfu** [comment] 2022-05-31 06:04
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-05-31 06:04 UTC
