### ISSUE TITLE
vue使用external方式引入的话，插件好像是不能使用的

### ISSUE THREAD

**Issue by MakeBetterMe** [antfu/unplugin-auto-import#100] opened 2021-12-28 02:44 UTC
vite + vue3项目

**Comment by sxzz** [comment] 2022-02-28 09:30
Needs reproduction.

**Comment by antfu** [comment] 2022-05-24 07:58
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2022-05-24 07:58 UTC
