### ISSUE TITLE
0.13.0开始无法启动vue3项目

### ISSUE THREAD

**Issue by kunimitsu2** [antfu/unplugin-auto-import#323] opened 2023-02-10 01:30 UTC
### Describe the bug

到0.12.2都可以正常使用，从0.13.0开始，启动项目后会报异常
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/46662803/217976359-f836ce4f-4972-404d-8ca4-aaeb2a7f10c2.png">
isFunction 没能正常导入，提示为undefined
<img width="822" alt="image" src="https://user-images.githubusercontent.com/46662803/217976496-32d66a7f-28d7-491d-8d61-61d6467a8cce.png">
is Function是从@vue/shared中导入的，其他函数也未能导入
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/46662803/217976612-9cd1b76e-ffb5-45d2-b021-04031dbfd99a.png">
降回0.12.2后可以正常使用

### Reproduction

无

### System Info

```Shell
"@vue/runtime-core": "^3.2.47",
"@vue/shared": "^3.2.47",
"@vueuse/core": "^9.12.0",
"@vueuse/shared": "^9.12.0",
"@zxcvbn-ts/core": "^2.2.1",
"ant-design-vue": "^3.2.15",
"@vitejs/plugin-legacy": "^4.0.1",
"@vitejs/plugin-vue": "^4.0.0",
"@vitejs/plugin-vue-jsx": "^3.0.0",
"@vue/compiler-sfc": "^3.2.47",
"vite": "^4.1.1",
"vue-tsc": "^1.0.24",
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by 1esse** [comment] 2023-02-16 09:59
解决了吗？我也遇到同样情况了

**Comment by lishaobos** [comment] 2023-02-17 07:26
我启动是 ok 的，请问可以提供可复现的 git 仓库吗？

**Comment by antfu** [comment] 2023-02-17 14:52
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-02-17 14:52 UTC

**Comment by kunimitsu2** [comment] 2023-02-20 09:12
git 源码: https://gitee.com/cao_zheng_zhe/v3-demo.git

**Comment by menghany** [comment] 2023-03-08 01:40
same problem
