### ISSUE TITLE
can not generate d.ts in nextjs

### ISSUE THREAD

**Issue by moliyu** [antfu/unplugin-auto-import#125] opened 2022-02-14 04:39 UTC

**Comment by moliyu** [comment] 2022-02-14 04:40
here is my config
~~~
/** @type {import('next').NextConfig} */
const withLess = require('next-with-less')
const AutoImport = require('unplugin-auto-import/webpack')
const { resolve } = require('path')
// const nextConfig = {
//   reactStrictMode: true,
// }

module.exports = withLess({
  reactStrictMode: true,
  lessLoaderOptions: {
    lessOptions: {
      javascriptEnabled: true
    },
  },
  webpack: config => {
    config.plugins.push(AutoImport({
      imports: ['react'],
      // dts: resolve(__dirname, 'auto-imports.d.ts')
    }))
    return config
  }
})

~~~

**Comment by antfu** [comment] 2022-02-14 06:55
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2022-02-14 06:55 UTC

**Comment by TrungRueta** [comment] 2022-02-14 08:30
@antfu @moliyu 
Hi Antfu, moliyu.
I can confirm Moliyu's issue. I created new fresh latest Nextjs and add auto-import webpack plugin, serve alias for package `classnames` as default import and plugin not render d.ts file.

This is codesandbox.
`https://codesandbox.io/s/nextjs-unplugin-auto-import-hg3sj?file=/pages/index.js`

Can you help review this case. 

Thank!
