### ISSUE TITLE
使用 ant-design-vue，在 a-modal 组件中，加了destroyOnClose 属性，在关闭弹窗时，.ant-modal-wrap 这个 dom 节点并没有自动添加 display:none。导致弹窗消失后遮罩还在，页面无法正常使用。 

### ISSUE THREAD

**Issue by upJiang** [antfu/unplugin-auto-import#168] opened 2022-04-24 02:27 UTC
"ant-design-vue": "2.2.8",
"unplugin-auto-import": "^0.6.9",
"unplugin-vue-components": "^0.18.4",
"vite-plugin-style-import": "^2.0.0",

**Comment by antfu** [comment] 2022-05-31 06:07
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-05-31 06:07 UTC

**Comment by 731ghyurt** [comment] 2025-03-21 10:06
解决了吗，我也遇到了这个问题
