### ISSUE TITLE
not supported '@vitejs/plugin-react-swc', I debug error

### ISSUE THREAD

**Issue by wgsheng06** [antfu/unplugin-auto-import#379] opened 2023-05-22 10:17 UTC
### Describe the bug

not supported '@vitejs/plugin-react-swc', I test chrome debugger error

# build/index.ts
`
import type { PluginOption } from 'vite';
import UnPlugin from './unplugin';
import react from '@vitejs/plugin-react-swc';
//import react from '@vitejs/plugin-react-refresh';

export function setupVitePlugins(
  viteEnv: ImportMetaEnv
): (PluginOption | PluginOption[])[] {
  return [react(), UnPlugin(viteEnv)];
}
`

# build/build.ts
`
import { getSrcPath } from '../utils';
import AutoImport from 'unplugin-auto-import/vite';

const UnPlugin = (viteEnv: ImportMetaEnv) => {
  const srcPath = getSrcPath();

  return AutoImport({
    dts: 'typings/auto-imports.d.ts',
    imports: ['react', 'react-i18next'],
  });
};
export default UnPlugin;
`

### Reproduction

not supported '@vitejs/plugin-react-swc', I test chrome debugger error

### System Info

```Shell
windows10
last two browsers

# package.json
{
  "name": "react-app",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "dev:mock": "vite --mode mock",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@dnd-kit/core": "^6.0.8",
    "@dnd-kit/sortable": "^7.0.2",
    "@dnd-kit/utilities": "^3.2.1",
    "@reduxjs/toolkit": "^1.9.5",
    "@tweenjs/tween.js": "^20.0.3",
    "@types/react-redux": "^7.1.25",
    "ahooks": "^3.7.6",
    "antd": "^5.4.6",
    "axios": "^1.4.0",
    "dayjs": "^1.11.7",
    "lodash": "^4.17.21",
    "react": "^18.2.0",
    "react-amap": "^1.2.8",
    "react-animated-number": "^0.4.4",
    "react-beautiful-dnd": "^13.1.1",
    "react-dom": "^18.2.0",
    "react-redux": "^8.0.5",
    "socket.io-client": "^4.6.1"
  },
  "devDependencies": {
    "@types/antd": "^1.0.0",
    "@types/axios": "^0.14.0",
    "@types/lodash": "^4.14.194",
    "@types/node": "^18.15.12",
    "@types/react": "^18.0.37",
    "@types/react-beautiful-dnd": "^13.1.4",
    "@types/react-dom": "^18.0.11",
    "@types/socket.io-client": "^3.0.0",
    "@vitejs/plugin-react-refresh": "^1.3.6",
    "@vitejs/plugin-react-swc": "^3.3.0",
    "less": "^4.1.3",
    "node-ts": "^6.0.0",
    "typescript": "^4.9.5",
    "unplugin-auto-import": "^0.16.0",
    "vite": "^4.3.0"
  }
}
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-05-22 16:52
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-05-22 16:52 UTC
