### ISSUE TITLE
Antd 4.0 introduced new components, but there is a warning in the console due to the unconfigured unplugin-auto-import plugin.

### ISSUE THREAD

**Issue by Yacj** [antfu/unplugin-auto-import#370] opened 2023-05-08 07:32 UTC
### Describe the bug

Antd 4.0 introduced new components, but there is a warning in the console due to the unconfigured unplugin-auto-import plugin
![QQ图片20230508152811](https://user-images.githubusercontent.com/11175513/236762309-d0793a78-f296-4ecc-90da-7861ce5ae2ad.png)

### Reproduction

If Antd 4.0 beta version and the unplugin-auto-import plugin are used in the project, there will be an issue when importing the Segmented component

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
  Browsers:
    Edge: Spartan (44.22621.1555.0), Chromium (112.0.1722.68)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lishaobos** [comment] 2023-05-23 03:45
need reproduction

**Comment by antfu** [comment] 2023-05-23 11:10
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-05-23 11:10 UTC
