### ISSUE TITLE
0.13.0 开始 vue3 项目 无法启动

### ISSUE THREAD

**Issue by kunimitsu2** [antfu/unplugin-auto-import#326] opened 2023-02-20 09:17 UTC
git 源码: https://gitee.com/cao_zheng_zhe/v3-demo.git

_Originally posted by @kunimitsu2 in https://github.com/antfu/unplugin-auto-import/issues/323#issuecomment-1436596296_

**Comment by antfu** [comment] 2023-02-20 11:00
This is not a **minimal reproduction**.

We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-02-20 11:00 UTC
