### ISSUE TITLE
Auto import not working on imported vue plugins

### ISSUE THREAD

**Issue by RuBaWa** [antfu/unplugin-auto-import#280] opened 2022-10-13 11:32 UTC
### Describe the bug

I am writing a Vue3 plugin. There i use for development at plugin project auto imports, what is working well for example with vueuse and useDark composable. I can use it whithout import.

In the project, where i want to test and import my plugin, i get errors, that useDark and other imports are missing, when they are used in files of my plugin under node_modules. In project auto-import.d.ts useDark is referencing to vueuse, which is also installed in test project. I thougt, that if it is loaded globally, my plugin which is also installed in node_modules, will find auto-imports too. 

Am i wrong with that? Or is it possible to extend resolution of auto imports to also work in files under node_modules?
Or do i have to include ts file type? I tried it with include [/\.ts$/,], but it doesn't change anything.

If i change my plugin to manually import, error is gone. So auto-import not detecting auto-imports of my plugin.

vite.config.js
```
// https://github.com/antfu/unplugin-auto-import
    AutoImport({
      include: [
        /\.[tj]sx?$/, // .ts, .tsx, .js, .jsx
        /\.vue$/,
        /\.vue\?vue/, // .vue
        /\.md$/, // .md
      ],
      imports: ['vue', 'vue-router', 'vue-i18n', 'vue/macros', '@vueuse/head', '@vueuse/core'],
      dirs: [
        './src/composables',
        //'./src/services'
      ],
      dts: true,
    }),
```

auto-import.d.ts
```
const useDark: typeof import('@vueuse/core')['useDark']
```

node_modules/my-plugin/src/folder/composable.ts
```
export const isDark = useDark({
  selector: 'html',
  attribute: 'theme',
  valueDark: 'dark',
  valueLight: 'light',
});
export const toggleDark = useToggle(isDark);
```
Error
```
ReferenceError: useDark is not defined
```

### Reproduction

I can't provide a codesandbox example, because it is an internal company plugin, but it should be the same behaviour at every plugin which is using auto-import.

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz 
    Memory: 14.03 GB / 31.72 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE        
    Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 106.0.5249.103
    Edge: Spartan (44.19041.1266.0), Chromium (106.0.1370.34)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vacnex** [comment] 2022-10-13 15:12
![image](https://user-images.githubusercontent.com/37587399/195636071-64837682-53a7-41d7-9afb-7ae9d6d474f1.png)
I has same issue too

**Comment by azaleta** [comment] 2022-10-14 02:35
@RuBaWa 
https://github.com/antfu/unplugin-auto-import/blob/5c27ac36ee57927aa6a09d11ee19d100fe2eab59/src/types.ts#L130-L135

**Comment by azaleta** [comment] 2022-10-14 02:39
@vacnex 
This is not the same problem I think.
Do you set this flag in your config?
![image](https://user-images.githubusercontent.com/22554452/195749545-88163e2f-9fe1-4d40-9b8a-4cbb629659ad.png)

**Comment by RuBaWa** [comment] 2022-10-14 06:52
> vacnex

Hey, thanks for your feedback. I have a mixed import of my plugin. I want to use components by vue.use with cjs files and import some helper, configs and composables manually by import from src folder. 

Manually overwrite "excludes" doesn't help. 

Its my first vue plugin, so maybe its a bad practice to use auto-imports at plugin development. I will rewrite my plugin to use manual imports again.

**Comment by antfu** [comment] 2023-02-07 10:32
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-02-07 10:32 UTC
