### ISSUE TITLE
element-ui auto imports doesn't seem right

### ISSUE THREAD

**Issue by tlyboy** [antfu/unplugin-auto-import#330] opened 2023-02-26 10:10 UTC
### Describe the bug

![image](https://user-images.githubusercontent.com/95838362/221404159-64d84034-f04e-4f5a-9949-63cd3942499c.png)
![image](https://user-images.githubusercontent.com/95838362/221404169-200b84ec-496a-4021-b95c-30a8e7d8f5b4.png)

### Reproduction

vite3 vue2 sass element-ui

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 20.33 GB / 31.86 GB
  Binaries:
    Node: 16.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.56)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Web0706** [comment] 2023-02-26 10:12
快点  急急急!!!

**Comment by lishaobos** [comment] 2023-05-23 05:49
需要一个可复现的 git 仓库

**Comment by antfu** [comment] 2023-05-23 11:09
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-05-23 11:09 UTC
