### ISSUE TITLE
Duplicate imports when using `import as` syntax.

### ISSUE THREAD

**Issue by Zolyn** [antfu/unplugin-auto-import#127] opened 2022-02-15 00:22 UTC
![2022-02-15_05-41](https://user-images.githubusercontent.com/35414841/153968036-079609ff-fca8-4479-bedf-157d3b214a01.png)
The content transformed by `@vitejs/plugin-vue` imported `defineComponent` from vue and renamed it to `_defineComponent`. Ideally, auto-import will not transform it. But the fact is that it will.

**Comment by He110te4m** [comment] 2022-03-01 01:39
Hello, I'm a little presumptuous, but can you tell me which software this is?

**Comment by antfu** [comment] 2022-03-01 03:03
@He110te4m https://github.com/antfu/vite-plugin-inspect

**Comment by antfu** [comment] 2022-03-01 03:03
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2022-03-01 03:03 UTC
Labels: need reproduction

**Comment by sxzz** [comment] 2022-03-01 09:44
```ts
import { ref as _ref } from 'vue'
```
The plugin will still add ```import { ref } from 'vue';``` , I think it should be avoided.

But in this case, the `ref` should be added again.

```ts
import { ref as _ref } from 'vue'

ref('a')
```

**Comment by Zolyn** [comment] 2022-03-01 11:12
[Minimal reproduction](https://github.com/Zolyn/auto-import-repro)
![2022-03-01_19-06](https://user-images.githubusercontent.com/35414841/156158921-11cbaf35-44d8-4a43-860a-aa90742150e0.png)
![2022-03-01_19-06_1](https://user-images.githubusercontent.com/35414841/156158933-bd198ba9-ee26-4a19-b2f2-b0694e8a0e4a.png)

**Comment by He110te4m** [comment] 2022-03-02 01:33
> @He110te4m https://github.com/antfu/vite-plugin-inspect

Thanks. This is very helpful for me.
