### ISSUE TITLE
启用热更新功能后，会导致按需加载的资源丢失

### ISSUE THREAD

**Issue by weipxiu** [antfu/unplugin-auto-import#204] opened 2022-06-12 15:27 UTC
用element plus按需加载组件，vite启用热更新功能后，在编辑器编写代码过程中，会导致按需加载的Message、MessageBox相关组件样式丢失，这似乎是插件resolvers的bug

**Comment by antfu** [comment] 2022-06-12 23:40
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-06-12 23:40 UTC
