### ISSUE TITLE
Local composables are not imported automatically

### ISSUE THREAD

**Issue by lautiamkok** [antfu/unplugin-auto-import#203] opened 2022-06-10 03:52 UTC
Custom/ local composables are not imported automatically. For example:

```
// vite.config.js
AutoImport({
      imports: [
        'vue',
        'vue-router',
      ],

      dirs: [
        'src/composables'
      ],
}),
```

Creating the composables, for example:

```
// src/composables/use-foo.js
export function useA () {
  return 'a'
}
```

Using the composables, for example:

```
// App.vue
<script setup>
const a = useA()
</script>
```

Errors on the Consol tab:

```
chunk-BPFSQ7MV.js?v=556b9e27:1262 [Vue warn]: Unhandled error during execution of setup function 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {__v_skip: true} > > 
  at <RouterView> 
  at <App>
warn2 @ chunk-BPFSQ7MV.js?v=556b9e27:1262
logError @ chunk-BPFSQ7MV.js?v=556b9e27:1416
handleError @ chunk-BPFSQ7MV.js?v=556b9e27:1408
(anonymous) @ chunk-BPFSQ7MV.js?v=556b9e27:2343
Promise.catch (async)
registerDep @ chunk-BPFSQ7MV.js?v=556b9e27:2342
mountComponent @ chunk-BPFSQ7MV.js?v=556b9e27:5056
processComponent @ chunk-BPFSQ7MV.js?v=556b9e27:5028
patch @ chunk-BPFSQ7MV.js?v=556b9e27:4742
componentUpdateFn @ chunk-BPFSQ7MV.js?v=556b9e27:5194
run @ chunk-BPFSQ7MV.js?v=556b9e27:399
callWithErrorHandling @ chunk-BPFSQ7MV.js?v=556b9e27:1363
flushJobs @ chunk-BPFSQ7MV.js?v=556b9e27:1555
Promise.then (async)
queueFlush @ chunk-BPFSQ7MV.js?v=556b9e27:1470
queueJob @ chunk-BPFSQ7MV.js?v=556b9e27:1464
(anonymous) @ chunk-BPFSQ7MV.js?v=556b9e27:5216
triggerEffects @ chunk-BPFSQ7MV.js?v=556b9e27:567
triggerRefValue @ chunk-BPFSQ7MV.js?v=556b9e27:1068
(anonymous) @ chunk-BPFSQ7MV.js?v=556b9e27:1192
triggerEffects @ chunk-BPFSQ7MV.js?v=556b9e27:567
triggerRefValue @ chunk-BPFSQ7MV.js?v=556b9e27:1068
(anonymous) @ chunk-BPFSQ7MV.js?v=556b9e27:1192
triggerEffects @ chunk-BPFSQ7MV.js?v=556b9e27:567
triggerRefValue @ chunk-BPFSQ7MV.js?v=556b9e27:1068
(anonymous) @ chunk-BPFSQ7MV.js?v=556b9e27:1192
triggerEffects @ chunk-BPFSQ7MV.js?v=556b9e27:567
triggerRefValue @ chunk-BPFSQ7MV.js?v=556b9e27:1068
(anonymous) @ chunk-BPFSQ7MV.js?v=556b9e27:1192
triggerEffects @ chunk-BPFSQ7MV.js?v=556b9e27:567
triggerRefValue @ chunk-BPFSQ7MV.js?v=556b9e27:1068
set value @ chunk-BPFSQ7MV.js?v=556b9e27:1111
finalizeNavigation @ vue-router.js?v=556b9e27:2289
(anonymous) @ vue-router.js?v=556b9e27:2206
Promise.then (async)
pushWithRedirect @ vue-router.js?v=556b9e27:2192
push @ vue-router.js?v=556b9e27:2145
install @ vue-router.js?v=556b9e27:2406
use @ chunk-BPFSQ7MV.js?v=556b9e27:4216
(anonymous) @ main.js:9
index.vue:13 Uncaught (in promise) ReferenceError: useA is not defined
    at setup (index.vue:13:11)
    at callWithErrorHandling (chunk-BPFSQ7MV.js?v=556b9e27:1363:18)
    at setupStatefulComponent (chunk-BPFSQ7MV.js?v=556b9e27:6569:25)
    at setupComponent (chunk-BPFSQ7MV.js?v=556b9e27:6533:36)
    at mountComponent (chunk-BPFSQ7MV.js?v=556b9e27:5050:7)
    at processComponent (chunk-BPFSQ7MV.js?v=556b9e27:5028:9)
    at patch (chunk-BPFSQ7MV.js?v=556b9e27:4742:11)
    at ReactiveEffect.componentUpdateFn [as fn] (chunk-BPFSQ7MV.js?v=556b9e27:5194:9)
    at ReactiveEffect.run (chunk-BPFSQ7MV.js?v=556b9e27:399:19)
    at callWithErrorHandling (chunk-BPFSQ7MV.js?v=556b9e27:1363:32)
```

What have I missed?

**Comment by antfu** [comment] 2022-06-10 06:10
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-06-10 06:10 UTC
