### ISSUE TITLE
Error: Cannot find module 'node:module'

### ISSUE THREAD

**Issue by franose371** [antfu/unplugin-auto-import#309] opened 2023-01-13 02:05 UTC
### Describe the bug

After running `npm install`, `npm run dev`, the error log:
```
Error: Cannot find module 'node:module'
Require stack:
- D:\code\demo1\node_modules\mlly\dist\index.cjs
- D:\code\demo1\node_modules\unimport\dist\shared\unimport.3a91e07e.cjs
- D:\code\demo1\node_modules\unimport\dist\addons.cjs
- D:\code\demo1\node_modules\unplugin-auto-import\dist\chunk-RZ4AY52Q.js
- D:\code\demo1\node_modules\unplugin-auto-import\dist\webpack.js
- D:\code\demo1\vue.config.js
- D:\code\demo1\node_modules\@vue\cli-shared-utils\lib\module.js
- D:\code\demo1\node_modules\@vue\cli-shared-utils\index.js
- D:\code\demo1\node_modules\@vue\cli-service\bin\vue-cli-service.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\code\demo1\node_modules\mlly\dist\index.cjs:4:21)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
```

### Reproduction

npm install & npm run dev

### System Info

```Shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 2.80 GB / 15.71 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (108.0.1462.54)
    Internet Explorer: 11.0.22000.120
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kalimah-apps** [comment] 2023-01-15 10:33
Your node version is 14. Try to update it to 16.

**Comment by antfu** [comment] 2023-02-07 10:31
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-02-07 10:31 UTC
