### ISSUE TITLE
打包后的 external 失效

### ISSUE THREAD

**Issue by BTBMan** [antfu/unplugin-auto-import#229] opened 2022-07-12 05:53 UTC
vite配置了externals 把vue等第三方库external掉 打包后的文件并没有把vue排除

<img width="489" alt="图片" src="https://user-images.githubusercontent.com/26108004/178417546-f6f5f8fe-a47b-4a8b-85bf-f47d828696a9.png">

此时reactive是auto-import定义好的

但在打包后 并没有把vue external掉
<img width="541" alt="图片" src="https://user-images.githubusercontent.com/26108004/178418229-daabbc52-aba8-490f-b6f7-5b8fa4bd5d5f.png">

**Comment by antfu** [comment] 2022-07-12 06:14
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-07-12 06:14 UTC

**Comment by BTBMan** [comment] 2022-07-12 13:04
复现了一下 发现不是本插件的问题 抱歉打扰了 😅
