### ISSUE TITLE
Bug: nested template literals.

### ISSUE THREAD

**Issue by leo-buneev** [antfu/unplugin-auto-import#123] opened 2022-02-10 09:59 UTC
Hi! Great library.

I've encountered an issue with detecting usage of autoimported variables. If there's nested template literal, all autoimported vars after it won't be detected and autoimport won't happen. Consider following example:

```
// config
    autoImport({
      imports: [
        {
          lodash: [['default', '_']],
        },
      ],
    }),
    
// code
const values = [1,2,3]
const string = `List of values: ${values.map(x => `'${x}'`).join(', ')}`
const minValue = _.min([1,2,3]) // _ won't be detected and autoimport won't happen
```

**Comment by sxzz** [comment] 2022-02-28 09:34
I can't reproduce it.

**Comment by antfu** [comment] 2022-05-24 07:58
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed** 2022-05-24 07:58 UTC

**Comment by leo-buneev** [comment] 2022-05-24 16:37
Here's the repro: https://stackblitz.com/edit/vite-hmbiei?file=main.js

**Comment by leo-buneev** [comment] 2022-05-24 16:42
Just noticed that matching logic was migrated to https://github.com/unjs/unimport. Should I open issue there instead?
