### ISSUE TITLE
when vue@3.2.27  npm err 

### ISSUE THREAD

**Issue by Web-Li** [antfu/unplugin-auto-import#226] opened 2022-07-07 06:52 UTC
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: vue3-vite@0.0.0
npm ERR! Found: vue@3.2.37
npm ERR! node_modules/vue
npm ERR!   vue@"^3.2.25" from the root project
npm ERR!   peer vue@"^2.6.0 || ^3.2.0" from @vueuse/core@8.7.5
npm ERR!   node_modules/@vueuse/core
npm ERR!     peer @vueuse/core@"*" from unplugin-auto-import@0.9.1
npm ERR!     node_modules/unplugin-auto-import
npm ERR!       dev unplugin-auto-import@"*" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vue@">= 2.5 < 3" from @vue/composition-api@1.6.3
npm ERR! node_modules/@vue/composition-api
npm ERR!   peer @vue/composition-api@"^1.1.0" from @vueuse/core@8.7.5
npm ERR!   node_modules/@vueuse/core
npm ERR!     peer @vueuse/core@"*" from unplugin-auto-import@0.9.1
npm ERR!     node_modules/unplugin-auto-import
npm ERR!       dev unplugin-auto-import@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by antfu** [comment] 2022-07-07 08:23
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-07-07 08:23 UTC

**Comment by Web-Li** [comment] 2022-07-07 08:49
$ npm init vite@latest demo-- --template vue

i choosed vue3

$ cd demo
$ npm install 
Everything is ok... my project run well

$ npm install -D unplugin-auto-import

I got an err tips:
npm ERR! Could not resolve dependency:
npm ERR! peer vue@">= 2.5 < 3" from @vue/composition-api@1.6.3

my verisons
node version: v16.15.1
npm version: 8.10.0
