### ISSUE TITLE
why my auto-imports.d.ts file only in the src folder can work?

### ISSUE THREAD

**Issue by facexl** [antfu/unplugin-auto-import#223] opened 2022-07-06 01:08 UTC

**Comment by antfu** [comment] 2022-07-06 02:04
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-07-06 02:04 UTC
