### ISSUE TITLE
auto import failed

### ISSUE THREAD

**Issue by BeADre** [antfu/unplugin-auto-import#209] opened 2022-06-17 09:17 UTC
```js
// vite.config.js
AutoImport({
  // ...
  dirs:['./src/example.js']
})

// example.js
export const a = () => {}
export const b = () => {}
```
```html
// app.vue
<script setup>
const method  = true ? a : b // get a error `ReferenceError: a is not defined`

// ----------------

let method

if (true) {
  method = a
} else {
  method = b
}
// running well
</script>

<template>
...
</template>
```

**Comment by antfu** [comment] 2022-06-17 09:31
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-06-17 09:31 UTC

**Comment by BeADre** [comment] 2022-06-17 09:52
@antfu sry... here is [reproduction](https://github.com/BeADre/autoImportTest)
