### ISSUE TITLE
ESLint: SyntaxError: Cannot read config file: ***\.eslintrc-auto-import.json

### ISSUE THREAD

**Issue by cjq02** [antfu/unplugin-auto-import#143] opened 2022-03-18 06:41 UTC
I run eslint --fix on save in my project, and the error tip(picture below) is always display when I save a file.It seems that .eslintrc-auto-import.json was regenerated during hot deployment in vue3/vite project.

The error stack information is as follows:
```
SyntaxError: Cannot read config file: D:\sizai\git\meeting\meeting-vue\.eslintrc-auto-import.json
Error: Unexpected end of JSON input
Referenced from: D:\sizai\git\meeting\meeting-vue\.eslintrc.js

SyntaxError: Cannot read config file: D:\sizai\git\meeting\meeting-vue\.eslintrc-auto-import.json
Error: Unexpected end of JSON input
Referenced from: D:\sizai\git\meeting\meeting-vue\.eslintrc.js
    at JSON.parse (<anonymous>)
    at loadJSONConfigFile (D:\sizai\git\meeting\meeting-vue\node_modules\.pnpm\@eslint+eslintrc@0.4.3\node_modules\@eslint\eslintrc\lib\config-array-factory.js:180:21)
    at loadConfigFile (D:\sizai\git\meeting\meeting-vue\node_modules\.pnpm\@eslint+eslintrc@0.4.3\node_modules\@eslint\eslintrc\lib\config-array-factory.js:315:20)
    at ConfigArrayFactory._loadConfigData (D:\sizai\git\meeting\meeting-vue\node_modules\.pnpm\@eslint+eslintrc@0.4.3\node_modules\@eslint\eslintrc\lib\config-array-factory.js:609:42)
    at ConfigArrayFactory._loadExtendedShareableConfig (D:\sizai\git\meeting\meeting-vue\node_modules\.pnpm\@eslint+eslintrc@0.4.3\node_modules\@eslint\eslintrc\lib\config-array-factory.js:889:21)
    at ConfigArrayFactory._loadExtends (D:\sizai\git\meeting\meeting-vue\node_modules\.pnpm\@eslint+eslintrc@0.4.3\node_modules\@eslint\eslintrc\lib\config-array-factory.js:781:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (D:\sizai\git\meeting\meeting-vue\node_modules\.pnpm\@eslint+eslintrc@0.4.3\node_modules\@eslint\eslintrc\lib\config-array-factory.js:720:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (D:\sizai\git\meeting\meeting-vue\node_modules\.pnpm\@eslint+eslintrc@0.4.3\node_modules\@eslint\eslintrc\lib\config-array-factory.js:665:20)
    at _normalizeObjectConfigData.next (<anonymous>)
```
![image](https://user-images.githubusercontent.com/16457309/158949815-b5c6135e-a411-46e2-b867-d32d5908f599.png)

**Comment by antfu** [comment] 2022-03-18 08:00
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2022-03-18 08:00 UTC
