### ISSUE TITLE
Failed to resolve directive: on-click-outside  (Cannot use directive)

### ISSUE THREAD

**Issue by anburocky3** [antfu/unplugin-auto-import#264] opened 2022-09-09 17:01 UTC
### Describe the bug

>  [Vue warn]: Failed to resolve directive: on-click-outside 

These are my config:

```ts
// vite.config.ts
AutoImport({
      imports: [
        // presets
        "vue",
        "vue-router",
        {
          "@vueuse/core": [
            "useMouse", 
          ],
          "@vueuse/components": ["vOnClickOutside"], // imported the vOnClickOutside
        },
      ],
      dts: "src/auto-imports.d.ts",
})
```

```ts
// auto-imports.d.ts
  const vOnClickOutside: typeof import('@vueuse/components')['vOnClickOutside']
```

```html
<div
  v-on-click-outside="() => (quickLinkBtn = false)">
</div>
```

### Reproduction

Use the above code to test.

### System Info

```Shell
System:
    OS: Windows 10 10.0.25193
    CPU: (32) x64 AMD Ryzen 9 3950X 16-Core Processor
    Memory: 18.58 GB / 31.92 GB
  Binaries:
    Node: 16.16.0 - S:\laragon\bin\nodejs\node-v16.16.0-win-x64\node.EXE
    Yarn: 1.22.19 - S:\laragon\bin\nodejs\node-v16.16.0-win-x64\yarn.CMD
    npm: 8.11.0 - S:\laragon\bin\nodejs\node-v16.16.0-win-x64\npm.CMD
  Browsers:
    Edge: Spartan (44.25193.1000.0), Chromium (104.0.1293.70)
    Internet Explorer: 11.0.25193.1000
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by azaleta** [comment] 2022-09-10 19:40
![image](https://user-images.githubusercontent.com/22554452/189499273-b48b0ffa-c50f-4a9a-8214-174bed1ed36a.png)
this is in template

**Comment by anburocky3** [comment] 2022-09-10 19:42
@azaleta I already have that, enabled.

![image](https://user-images.githubusercontent.com/15264938/189499342-66fa911a-e91b-411c-9333-ef580a7bb5d5.png)

**Comment by azaleta** [comment] 2022-09-11 18:32
first, this should be process in unplugin-vue-template(not in unplugin-auto-import).
And also, currently it has a bug.
Please wait this PR and reconfirm
https://github.com/antfu/unplugin-vue-components/pull/509

**Comment by antfu** [comment] 2023-02-07 10:33
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-02-07 10:33 UTC
