### ISSUE TITLE
I got the error after up to version 0.10.2

### ISSUE THREAD

**Issue by sctouch** [antfu/unplugin-auto-import#242] opened 2022-07-28 14:11 UTC
### Describe the bug

nuxt: 2.15.8
unplugins-auto-import: 0.10.2

After updating the package to version `0.10.2`, I got the following error
<img width="1630" alt="image" src="https://user-images.githubusercontent.com/53075504/181525916-bb308362-c264-4d6b-b232-72119e364dd7.png">

### Reproduction

Just update the package and run yarn dev

### System Info

```Shell
System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 2.03 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Safari: 15.5
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2022-07-29 11:38
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-07-29 11:38 UTC

**Comment by sctouch** [comment] 2022-08-03 06:31
Yes, but It's simply happen on nuxt 2, so sad.
