### ISSUE TITLE
can not success run  at v0.8.6

### ISSUE THREAD

**Issue by kalfbz** [antfu/unplugin-auto-import#192] opened 2022-06-01 07:07 UTC
error message "if (source.startsWith("webpack://")) return source unplugin-auto-import"

**Comment by kalfbz** [comment] 2022-06-01 07:09
success run at v0.6.9

@vue/cli 5.0.4

**Comment by antfu** [comment] 2022-06-01 08:22
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-06-01 08:22 UTC
