### ISSUE TITLE
error during build: RollupError: 'import' and 'export' may only appear at the top level (Note that you need plugins to import files that are not JavaScript)

### ISSUE THREAD

**Issue by zongpengz** [antfu/unplugin-auto-import#315] opened 2023-02-01 05:29 UTC
当升级到v0.13.0后，打包出现这个错误。当我删除了一个在顶部的注释代码后，它正常了

**Comment by zongpengz** [comment] 2023-02-01 05:29
![image](https://user-images.githubusercontent.com/22546341/215959422-9a76262c-8735-4af6-ac47-e018563854ed.png)

**Comment by antfu** [comment] 2023-02-07 10:22
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-02-07 10:22 UTC
