### ISSUE TITLE
Build error with @vitejs/plugin-legacy

### ISSUE THREAD

**Issue by we125182** [antfu/unplugin-auto-import#177] opened 2022-05-17 14:40 UTC
UAI means unplugin-auto-import.

UAI import api on demand that it only import the api which is used while compile a page--[detail issue](https://github.com/element-plus/element-plus/issues/6947). but when I build a project width @vitejs/plugin-legacy, errors came up. it seems has priority execution before UAI.

notice that if we already met all pages, everything will be ok.

how to change UAI priority before @vitejs/plugin-legacy and avoid UAI delete dts file everytime rerun a project?

sorry for my poor english. and thank you for all help

**Comment by antfu** [comment] 2022-05-31 06:06
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-05-31 06:06 UTC
