### ISSUE TITLE
Ref这个api没有自动导入

### ISSUE THREAD

**Issue by li522021642** [antfu/unplugin-auto-import#364] opened 2023-04-19 09:27 UTC
### Describe the bug

Ref 这个api没有自动导入，auto-imports.d.ts中没有这个api

### Reproduction

无

### System Info

```Shell
window，chrome，vite，vue3
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-04-19 11:21
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-04-19 11:21 UTC
