### ISSUE TITLE
 The special project directory does not work correctly 工作目录有特殊字符导致无法正常构建

### ISSUE THREAD

**Issue by RedFlagRF** [antfu/unplugin-auto-import#335] opened 2023-03-01 01:58 UTC
### Clear and concise description of the problem

# Working directories with special characters affect plugin builds

## error situation
 jenkin deploy， work Directory: "xxx-TEST(frontend)"   , execute  `npm run build:test` ,it look build success, but lost auto-import  custom import directory file .
![Snipaste_2023-03-01_09-54-25](https://user-images.githubusercontent.com/48118178/222024651-dc1a24cc-e58e-4c78-8959-dc4b2aa53a5b.png)

## normal situation
 jenkin deploy， work Directory: "xxx-TEST-frontend"   , execute  `npm run build:test` ,it   build success 
![Snipaste_2023-03-01_09-44-52](https://user-images.githubusercontent.com/48118178/222023516-2db67116-2679-4d88-917d-7f782c781e95.png)

### Suggested solution

add  tips  to ReadMe  or  do something with build tips 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment] 2023-03-01 17:03
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-03-01 17:03 UTC
Labels: enhancement
