### ISSUE TITLE
What happens when a process blocks?

### ISSUE THREAD

**Issue by aliuq** [antfu/unplugin-auto-import#186] opened 2022-05-30 03:23 UTC
Hi

After updating from `0.7.1` to `0.8.6`, when I ran my project, it kept prompting me that it was compiling without success or error, after a long time of testing, I found that it was because there was a `navigateTo` method in the preset, which caused the process to block for some reason. In version `0.7.1`, `navigateTo` exists and works fine.

Similarly, there is a `navigateBack` method in the preset, and `navigateBack` has no effect

So, Is `navigateTo` a keyword?

+ Webpack 4
+ 小程序

**Comment by antfu** [comment] 2022-05-30 03:49
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2022-05-30 03:49 UTC

**Comment by aliuq** [comment] 2022-05-30 09:59
`navigateTo` is my mistake, it used by one page like this.

```vue
<script setup lang="ts">
function go(url: string) {
  navigateTo({ url })
}
</script>
```

I tested `0.8.x`, from version `0.8.0`, it can't works in webpack v4, I think it's possible that `unimport` may not be compatible in one place in webpack
