### ISSUE TITLE
enum 生成错误+注释的export也会生成

### ISSUE THREAD

**Issue by BryanAdamss** [antfu/unplugin-auto-import#253] opened 2022-08-17 03:48 UTC
### Describe the bug

```js
// vite.config.js

AutoImport({
      // targets to transform
      include: [
        /\.[tj]sx?$/, // .ts, .tsx, .js, .jsx
        /\.vue$/, /\.vue\?vue/, // .vue
      ],

      // global imports to register
      /* 自动导入vue、vue-router、pinia等API */
      imports: [
        // presets
        'vue',
        'vue-router',
        'pinia',
      ],

      // Auto import for all module exports under directories
      dirs: [
        'src/services/api',
        // './hooks',
        // './composables'
        // ...
      ],

      // Filepath to generate corresponding .d.ts file.
      // Defaults to './auto-imports.d.ts' when `typescript` is installed locally.
      // Set `false` to disable.
      dts: 'types/auto-imports.d.ts',

      // Auto import inside Vue template
      // see https://github.com/unjs/unimport/pull/15 and https://github.com/unjs/unimport/pull/72
      vueTemplate: false,

    }),

// src/services/api/common.ts
export const enum CommonApi {
  PREMISSION_QUERY = '/xxx/permission/query',
}

// 我被注释了💥
// export const commented = 'commented'

// auto-imports.d.ts
// Generated by 'unplugin-auto-import'
export {}
declare global {
  ...
 // 注释的也自动生成了(这似乎不是问题)
  const commented: typeof import('../src/services/api/common')['commented']
  ...
 // enum的生成错误💥
  const enum: typeof import('../src/services/api/common')['enum']
  ...
}
```

### Reproduction

参照描述

### System Info

```Shell
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 958.86 MB / 15.74 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 104.0.5112.81
    Edge: Spartan (44.18362.449.0)
    Internet Explorer: 11.0.18362.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by azaleta** [comment] 2022-08-18 09:34
enum
(https://github.com/unjs/mlly/pull/69)

**Comment by antfu** [comment] 2023-02-07 10:32
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-02-07 10:32 UTC
