### ISSUE TITLE
Vue3 tsx auto import invalid 

### ISSUE THREAD

**Issue by zz541843** [antfu/unplugin-auto-import#198] opened 2022-06-04 15:24 UTC
chrome
![image](https://user-images.githubusercontent.com/72638366/172011671-ecb60351-a2ba-443c-a4d0-2af08fb8ab95.png)
config
![image](https://user-images.githubusercontent.com/72638366/172011736-3164eaa8-12dd-4ef8-9b1c-ad43c75efe5f.png)
tsx
![image](https://user-images.githubusercontent.com/72638366/172011750-908512a1-1e8f-4a95-b9cc-bfaa4052451a.png)
![image](https://user-images.githubusercontent.com/72638366/172011759-3dd27d73-6493-456f-b858-96771b3e870e.png)

**Comment by antfu** [comment] 2022-06-04 15:27
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-06-04 15:28 UTC
