### ISSUE TITLE
如果script中的第一行是注释掉的import语句,将会导致渲染报错

### ISSUE THREAD

**Issue by lincenying** [antfu/unplugin-auto-import#329] opened 2023-02-26 09:17 UTC
### Describe the bug

```
<script setup name="test-general">
// import useMainStore from '@/pinia'

// eslint-disable-next-line no-unused-vars
const { ctx, options, proxy, route, router, globalStore, useLockFn } = useGlobal('test-general')
```
上面代码, 控制台将会报错, 错误信息如下图:
![image](https://user-images.githubusercontent.com/10840991/221401900-66bc3c8a-5ad1-4858-b0d7-4992d361daf8.png)

如果将`// import useMainStore from '@/pinia'` 删除, 或者将`import`改成`imp ort`, 将正常渲染

### Reproduction

vue文件中, 将script的第一行任意添加一行注释掉的import语句

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
    Memory: 6.45 GB / 15.87 GB
  Binaries:
    Node: 14.18.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-02-27 11:26
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-02-27 11:26 UTC

**Comment by lincenying** [comment] 2023-02-28 07:39
已添加示例代码仓库
