### ISSUE TITLE
项目引入新的依赖后，提示s.hasChanged is not a functiond

### ISSUE THREAD

**Issue by Mhist** [antfu/unplugin-auto-import#361] opened 2023-04-18 10:32 UTC
### Describe the bug

项目引入新的依赖后，提示s.hasChanged is not a functiond
at Object.transform (/opt/node_modules/unplugin-auto-import/dist/chunk-D3CKI5NO.cjs:195:12)

### Reproduction

re

### System Info

```Shell
1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-04-18 12:18
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-04-18 12:18 UTC
