### ISSUE TITLE
build error TS2304: Cannot find name XXX

### ISSUE THREAD

**Issue by davidchen27** [antfu/unplugin-auto-import#234] opened 2022-07-17 07:16 UTC
environment：
    Node: v16.14.0
    Vite: v2.19.12 - v3.0.0
    Vue: v3.2.37
    Typescript: v4.7.4
i use unplugin-auto-import, then run 'yarn run build'
get error message：
``` bash
src/views/home/index.vue:12:15 - error TS2304: Cannot find name 'useMainStore'.
src/layouts/admin_layout.vue:10:19 - error TS2304: Cannot find name 'storeToRefs'.
```

code: 
``` typescript
import { fileURLToPath, URL } from 'url'
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import AutoImport from 'unplugin-auto-import/vite'
import Components from 'unplugin-vue-components/vite'

// https://vitejs.dev/config/
export default defineConfig({
  server: {
    host: true
  },
  plugins: [
    vue(),
    AutoImport({
      imports: [
        {
          vue: ['ref', 'onMounted', 'computed'],
          pinia: ['storeToRefs', 'mapActions'],
          '@/stores/mainStore': ['useMainStore']
        }
      ],
      dirs: ['src/hooks'],
      eslintrc: {
        enabled: true,
        filepath: './.eslintrc-auto-import.json',
        globalsPropValue: 'readonly'
      },
      dts: 'types/auto-imports.d.ts'
    }),
    Components({
      dirs: ['src/components', 'src/layouts'],
      directoryAsNamespace: true,
      dts: 'types/components.d.ts'
    })
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  },
  css: {
    preprocessorOptions: {
      scss: {
        additionalData: '@import "@/styles/index.scss";'
      }
    }
  }
})
```
tsconfig.json
``` json
{
  "extends": "@vue/tsconfig/tsconfig.web.json",
  "include": ["types/*", "src/**/*", "src/**/*.vue"],
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "references": [
    {
      "path": "./tsconfig.config.json"
    }
  ]
}
```

**Comment by azaleta** [comment] 2022-07-17 08:29
src/views/home/index.vue:12:15
do you want to use them  in `<template>` ?

if so, add config `vueTemplate: true`

**Comment by davidchen27** [comment] 2022-07-17 08:46
> src/views/home/index.vue:12:15 do you want to use them in `<template>` ?
> 
> if so, add config `vueTemplate: true`

no，i use them in <script>, and only report errors when building..
![image](https://user-images.githubusercontent.com/44220311/179390939-36be3cf0-06c9-4c6c-a192-d5f469c9d24c.png)
it works in the Webstorm

**Comment by antfu** [comment] 2022-07-17 08:57
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-07-17 08:57 UTC

**Comment by mxismean** [comment] 2022-09-27 08:26
The same error.
I use pnpm.
<img width="431" alt="image" src="https://user-images.githubusercontent.com/44690729/192474332-464f601d-89d2-4862-a773-35b0391c41fe.png">

**Comment by mxismean** [comment] 2022-09-27 08:29
@antfu This configuration has been configured rightly, and the solutions found online have been tried, but an error is still reported

**Comment by azaleta** [comment] 2022-09-27 08:43
any reproduction?

**Comment by nyrf** [comment] 2022-10-15 10:57
Same error when use element-plus, and i found sometimes it build success and sometimes it got error.

**Comment by yhlchao** [comment] 2022-10-16 16:32
Add "./auto-imports.d.ts" into tsconfig.json, like this:
<img width="858" alt="img" src="https://user-images.githubusercontent.com/33980809/196047002-9274916a-1fe6-44dd-8878-48c0ffcd65c3.png">

it works for me.

**Comment by asdjgfr** [comment] 2022-10-21 06:48
> Same error when use element-plus, and i found sometimes it build success and sometimes it got error.

try move custome config after element plus, such as :
``` js
{
  plugins: [
    AutoImport({
      resolvers: [ElementPlusResolver()],
    }),
    Components({
      resolvers: [ElementPlusResolver()],
    }),
    AutoImport({
      // targets to transform
      include: [/\.[tj]sx?$/],
      // global imports to register
      imports: [
        // custom
        {
          [`@/locales/${defaultLang}`]: [
            // default imports
            ["default", "defaultMessages"], // import { default as defaultMessages } from '@/locales/${defaultLang}/index',
          ],
        },
      ],
      eslintrc: { enabled: true },
    }),
  ];
}

```

then add `auto-imports.d.ts` into `tsconfig.app.json` and `.eslintrc-auto-import.json` into `.eslintrc`

```js
// tsconfig.app.json

{
  extends: "@vue/tsconfig/tsconfig.web.json",
  include: [
    //...
    "auto-imports.d.ts",
  ],
  exclude: ["src/**/__tests__/*"],
  compilerOptions: {
    composite: true,
    baseUrl: ".",
    paths: {
      "@/*": ["./src/*"],
    },
    types: ["mocha", "chai"],
  },
}

```

```js
// eslint

{
  extends: [
   //...
    "./.eslintrc-auto-import.json",
  ],
}

```

**Comment by nyrf** [comment] 2022-10-22 04:30
@asdjgfr Thanks, i found that i run `pnpm build-only` first and then run `pnpm build`, it can works.

```
  "scripts": {
    "dev": "vite",
    "build": "run-p type-check build-only",
    "preview": "vite preview --port 4173",
    "build-only": "vite build",
    "type-check": "vue-tsc --noEmit",
    "lint": "eslint . --ext .vue,.js,.jsx,.cjs,.mjs,.ts,.tsx,.cts,.mts --fix --ignore-path .gitignore"
  },
```

**Comment by Developer27149** [comment] 2023-02-09 06:14
> The same error. I use pnpm. <img alt="image" width="431" src="https://user-images.githubusercontent.com/44690729/192474332-464f601d-89d2-4862-a773-35b0391c41fe.png">

把`auto-imports.d.ts`加到`tsconfig`的`includes`数组内即可

**Comment by latel** [comment] 2024-12-24 16:27
> > The same error. I use pnpm. <img alt="image" width="431" src="https://user-images.githubusercontent.com/44690729/192474332-464f601d-89d2-4862-a773-35b0391c41fe.png">
> 
> 把`auto-imports.d.ts`加到`tsconfig`的`includes`数组内即可

为什么开箱文档里完全没提呢？
