### ISSUE TITLE
<script setup lang="ts"> cannot find name 'onMounted'

### ISSUE THREAD

**Issue by mariusa** [antfu/unplugin-auto-import#138] opened 2022-03-13 09:32 UTC
`onMounted` works fine for `<script setup>` with vscode, no warnings.
`.eslintrc` has 
```
extends: ["eslint:recommended", "plugin:vue/base", "plugin:vue/vue3-essential", "plugin:vue/vue3-recommended", "plugin:vue/vue3-strongly-recommended", "@antfu"],
```
Adding `lang="ts"` makes vscode show warning `cannot find name 'onMounted'`, but `$ref` has no warning.

How to solve this?

Maybe related to https://github.com/antfu/unplugin-auto-import/issues/61 ?

**Comment by antfu** [comment] 2022-03-14 01:00
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2022-03-14 01:00 UTC

**Comment by mariusa** [comment] 2022-03-14 05:15
Looking at vitesse (thanks for it), found the solution: Add to `AutoImport` in vite config:
```
dts: 'src/auto-imports.d.ts',
```

**Comment by beierzhijin** [comment] 2022-11-10 09:54
same problem

**Comment by beierzhijin** [comment] 2022-11-10 10:34
add `*.d.ts` to `tsconfig.json`
```json
  // tsconfig.json
  "include": [
    "*.d.ts",
    "src/**/*.ts",
    "src/**/*.d.ts",
    "src/**/*.tsx",
    "src/**/*.vue"
  ],
```
