### ISSUE TITLE
Clearing cache and forcing full-reload to ensure TypeScript is compiled with updated config values

### ISSUE THREAD

**Issue by jiechen257** [antfu/unplugin-auto-import#421] opened 2023-08-17 08:44 UTC
### Describe the bug

This problem is always present when HMR occurs in multi-page applications

### Reproduction

trigger HMR in multi-page applications

### System Info

```Shell
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1
    Memory: 57.56 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
    pnpm: 7.33.0 - ~/Desktop/work-project/vtn-int-h5/node_modules/.bin/pnpm
  Browsers:
    Chrome: 116.0.5845.96
    Safari: 16.4
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-08-23 16:27
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-08-23 16:27 UTC
