### ISSUE TITLE
Automatically importing ref() will report a type error, but import { ref} from 'vue' will not.

### ISSUE THREAD

**Issue by tlerbao** [antfu/unplugin-auto-import#286] opened 2022-10-27 12:24 UTC
### Describe the bug

Please how to solve this problem

### auto import error
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/20442232/198283144-74457ed2-c12a-4b59-aa2e-e83d7e367003.png">

### but import { ref} from 'vue' will not.

<img width="762" alt="image" src="https://user-images.githubusercontent.com/20442232/198283300-838a4f34-47dd-43e9-af62-767a9ecbb77c.png">

### Reproduction

Reproduction

### System Info

```Shell
System:
    OS: macOS 12.5.1
    CPU: (12) x64 Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz
    Memory: 1.81 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Safari: 16.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by beierzhijin** [comment] 2022-11-10 10:15
same question

**Comment by oceangravity** [comment] 2023-02-04 18:46
Same here

**Comment by antfu** [comment] 2023-02-07 10:21
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-02-07 10:21 UTC

**Comment by oceangravity** [comment] 2023-02-07 10:44
I think this issue is related with IntelliJ or Webstorm IDEs, I opened my project in VSCode without trouble
