### ISSUE TITLE
Doesn't work in nuxt 2 for the latest version.

### ISSUE THREAD

**Issue by sctouch** [antfu/unplugin-auto-import#244] opened 2022-08-03 06:39 UTC
I got the error after updating it to the latest version.

**Comment by antfu** [comment] 2022-08-04 08:02
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-08-04 08:02 UTC
