### ISSUE TITLE
之前使用版本 0.7.1  升级0.8.5版本之后编译报错  Cannot read properties of null (reading 'startsWith') 

### ISSUE THREAD

**Issue by wowoName** [antfu/unplugin-auto-import#187] opened 2022-05-30 09:48 UTC
***\node_modules\unplugin-auto-import\node_modules\unplugin\dist\webpack\loaders\transform.js??ref--39-0!***\node_modules\unplugin-vue-components\node_modules\unplugin\dist\webpack\loaders\transform.js??ref--40-0!***\node_modules\unplugin-auto-import\node_modules\unplugin\dist\webpack\loaders\transform.js??ref--39-0***\node_modules\unplugin-vue-components\node_modules\unplugin\dist\webpack\loaders\transform.js??ref--40-0!***\node_modules\cache-loader\dist\cjs.js??ref--13-0!***\node_modules\babel-loader\lib\index.js!***\node_modules\cache-loader\dist\cjs.js??ref--1-0!***\node_modules\vue-loader-v16\dist\index.js??ref--1-1!***
Cannot read properties of null (reading 'startsWith')

**Comment by itskaiway** [comment] 2022-05-30 10:31
一样的问题，暂时把选项中的`imports: ['vue']`屏蔽，批量修改下页面导入vue的路径，问题解决，等待大佬解决吧

**Comment by antfu** [comment] 2022-05-30 16:37
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-05-30 16:37 UTC

**Comment by exherb** [comment] 2022-05-31 02:00
maybe related to https://github.com/dart-lang/sdk/issues/38967

https://github.com/antfu/unplugin-auto-import/blob/8b70cffee957b87a1c699c3c42d3ba0b986e1193/src/core/ctx.ts#L68

it's failed at

```javascript
{
  name: 'constructor',
  as: 'constructor',
  ___dart_isolate_tags_: [Object: null prototype] { _ZxYxX_0_: 1 }
}
```

**Comment by antfu** [comment] 2022-05-31 06:01
How's it sneak into the import list?

**Comment by exherb** [comment] 2022-06-06 03:05
no idea, but I add some log and print i with this.

**Comment by exherb** [comment] 2022-06-06 09:15
I have find the root cause of this issue.

```typescript
const unpluginResolver: ComponentResolver = {
    type: "component",
    resolve(name: string): ComponentResolveResult {
      const p = {"a": import("@/xxx/a")}[name];
      if (p != null) {
        return p;
      }
  };
```

when name is `constructor` or `toString`, it return `func`.
