### ISSUE TITLE
0.8版本后为啥报错require is not defined

### ISSUE THREAD

**Issue by date13** [antfu/unplugin-auto-import#196] opened 2022-06-04 13:22 UTC
升级到0.8后的版本,vue3+vite报错 ,0.7的版本是正确的
require is not defined

生成的源代码中
const { ref, onBeforeMount } = require('vue');

但是vite又不支持require.这个如何解决

**Comment by antfu** [comment] 2022-06-04 15:25
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-06-04 15:25 UTC
